/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rcalculations.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

double *
calculate_pi_1(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CALCULATE_PI, xdr_void, argp, xdr_double, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

double *
calculate_exp_1(argp, clnt)
	double *argp;
	CLIENT *clnt;
{
	static double clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, CALCULATE_EXP, xdr_double, argp, xdr_double, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
